version: '3.9'

services:
  postgres-db:
    container_name: estacionamento-postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "estacionamento"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: